version: "3"
services:
  nginx:
    image: nginx:alpine
    ports: 
      - "8080:80"
    networks:
      - sample
    volumes:
      - ./src:/var/www/html/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:8.2.2-fpm-alpine3.17
    networks:
      - sample
    volumes:
      - ./src:/var/www/html/src
      - ./vendor:/var/www/html/vendor

networks:
  sample:
    driver: bridge